# ───────────────────────────────────────────────────────────── 

# generate_dzn_from_nn.py  |  Neuro-Symbolic bridge script 

# Run BEFORE each planning cycle. Reads live battlefield context, 

# runs inference, and writes liberation_nn_predicted.dzn. 

# ───────────────────────────────────────────────────────────── 

import torch 

import pickle 

import numpy as np 

from opu_predictor import OPUPredictor    # import architecture class 

 

# ── 1. LOAD THE TRAINED MODEL ───────────────────────────────── 

# Step a: Instantiate the architecture (empty, random weights) 

model = OPUPredictor() 

 

# Step b: Load the saved weight dictionary into the empty model. 

#         torch.load() reads the binary .pt file from disk and 

#         returns the state_dict (a Python dict of tensors). 

#         load_state_dict() fills the model's layers with those tensors. 

model.load_state_dict(torch.load('opu_predictor_weights.pt', 

                                  map_location='cpu'))  # use CPU 

 

# Step c: Switch to evaluation mode (disables Dropout, enables determinism) 

model.eval() 

 

# ── 2. LOAD THE FEATURE SCALER (same object used during training) ── 

# IMPORTANT: you must use the SAME scaler that was fitted on training data. 

# If you refit a new scaler here, the feature distributions will differ 

# and predictions will be garbage (a common bug — known as 'data leakage'). 

with open('scaler.pkl', 'rb') as f: 

    scaler = pickle.load(f) 

 

# ── 3. READ LIVE BATTLEFIELD CONTEXT ───────────────────────── 

# In a real system this would query a classified API or database. 

# For illustration, we define it as a Python dictionary: 

battlefield_context = { 

    'terrain':    'urban_flatland',  # Kherson oblast 

    'season':     'winter', 

    'enemy_ADA':  0.7,               # 70% ADA coverage (HIGH — reduces UAV OPU) 

    'logistics':  0.85,              # 85% supply reliability 

    'visibility': 12.0,              # km (reduced by winter fog) 

    'sortie_rate': 0.85, 

    'maintenance': 0.90, 

} 

 

# Encoding maps: must match the LabelEncoder order used during training 

TERRAIN_MAP = {'urban_flatland': 0, 'forest': 1, 'open_steppe': 2, 'mountain': 3} 

SEASON_MAP  = {'spring': 0, 'summer': 1, 'autumn': 2, 'winter': 3} 

ASSET_MAP   = {'INF': 0, 'ARMR': 1, 'ARTY': 2, 'UAV': 3} 

 

# ── 4. PREDICT eOPU FOR EACH ASSET TYPE ────────────────────── 

asset_types = ['INF', 'ARMR', 'ARTY', 'UAV'] 

predicted_opu = [] 

 

for asset in asset_types: 

    # Build the raw 8-feature vector for this asset in this context 

    raw_features = np.array([[ 

        TERRAIN_MAP[battlefield_context['terrain']], 

        SEASON_MAP[battlefield_context['season']], 

        battlefield_context['enemy_ADA'], 

        battlefield_context['logistics'], 

        battlefield_context['visibility'] / 50.0,   # normalise 

        ASSET_MAP[asset], 

        battlefield_context['sortie_rate'], 

        battlefield_context['maintenance'], 

    ]]) 

 

    # Apply the SAME scaling used during training 

    scaled_features = scaler.transform(raw_features) 

 

    # Convert to tensor and run inference 

    input_tensor = torch.tensor(scaled_features, dtype=torch.float32) 

    with torch.no_grad():              # no gradient tracking = faster + less memory 

        eOPU = model(input_tensor).item()   # .item() extracts scalar from tensor 

 

    predicted_opu.append(round(eOPU, 2)) 

    print(f'  {asset:4s}  →  predicted eOPU = {eOPU:.2f}') 

 

# ── 5. WRITE THE .DZN FILE ──────────────────────────────────── 

# This file is fed directly to MiniZinc in the next step. 

# It uses exactly the same structure as liberation_generic_op1.dzn, 

# but with NN-predicted OPU values instead of hard-coded numbers. 

dzn_content = f""" 

% liberation_nn_predicted.dzn 

% AUTO-GENERATED by generate_dzn_from_nn.py  (DO NOT EDIT MANUALLY) 

% Battlefield context: {battlefield_context} 

 

ASSET = {{INF, ARMR, ARTY, UAV}}; 

 

% Predicted eOPU values from OPU Predictor MLP (context-specific) 

opu = {predicted_opu}; 

 

RESOURCE = {{Budget, Personnel}}; 

capacity = [10000000.0, 250000.0]; 

 

% Consumption matrix [ASSET x RESOURCE]  (Budget in USD, Personnel) 

consumption = [| 1300.0, 4000.0   % INF 

               | 2100.0,  800.0   % ARMR 

               | 1700.0,  300.0   % ARTY 

               |10000.0,  120.0   % UAV 

               |]; 

max_units = [1000, 400, 500, 150]; 

""".strip() 

 

with open('liberation_nn_predicted.dzn', 'w') as f: 

    f.write(dzn_content) 

 

print('\nGenerated: liberation_nn_predicted.dzn') 

print('OPU values:', dict(zip(asset_types, predicted_opu))) 